#!/usr/bin/env bash
#  _
# | |__  ___ _ ____      ___ __ ___  _ __ ___ 
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \| '__/ __|
# | |_) \__ \ |_) \ V  V /| | | | | | | | (__ 
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|_|  \___|
#           |_|

#█▓▒░  DISPLAY SETTINGS
. ./bspwm_monitor &
bspwm_monitor 5 FF1 1

#█▓▒░  BSPWM SETTINGS
bspc config center_pseudo_tiled        true
bspc config focus_follows_pointer      true
bspc config split_ratio                0.52

bspc config pointer_modifier           mod4
bspc config pointer_action1            move
bspc config pointer_action2            resize_corner

bspc config pointer_follows_monitor    true
bspc config pointer_follows_focus      true

bspc config borderless_monocle         false
bspc config gapless_monocle            false
bspc config single_monocle	           true

#█▓▒░  BSPWM STYLES
. ./bspwm_style &

#█▓▒░ WINDOW RULES
bspc rule -a *:floating state=floating

#█▓▒░ WORKSPACE SETTINGS
# bspc rule -a AppName desktop=^1 follow=on focus=on
# bspc rule -a AppName desktop=^2 follow=on focus=on

#█▓▒░ RESTART APPS
. ./autostart &