#!/usr/bin/env bash
#█▓▒░ IMPORT VARS
. "${HOME}/.cache/wal/colors.sh"

# bspc config border_radius            5
bspc config border_width               04
bspc config window_gap                 16
bspc config bottom_padding             00
bspc config left_padding               00
bspc config right_padding              00
bspc config top_padding                26

bspc config normal_border_color       "$color1"
bspc config active_border_color       "$color4"
bspc config focused_border_color      "$color2"
bspc config presel_feedback_color     "$color2"